### ISSUE TITLE
Reduce flicker while switching between weekdays

### ISSUE THREAD

**Issue by stormofice** [mensatt/frontend-old#93]
Clicking between different weekdays results in noticeable flicker.

https://user-images.githubusercontent.com/58337328/179084940-f72c4dfc-25d8-428f-8fd4-9e68cc4a6ae9.mp4

This seems to happen, because for a split second (while the data is being requested) there is a small loading screen where there are no white backgrounds. We can't really reduce the backends' response time, so we should think of a different way to minimze those artefacts.

Would it be possible to fade between the views to make the transition easier on the eyes?
Other ideas are also appreciated, as it is currently a little jarring to quickly check the food for different weekdays.

**Comment by GamerBene19** [comment]
This issue is known already (at least internally). The cause has been identified too - it's [this bit right here](https://github.com/mensatt/frontend/blob/ba4e3de07d09a5aabebaec977106ed63cc69d7bf/src/components/navigation/weekday-selection/WeekdaySelection.tsx#L47-L50). There also is a workaround that I'm not quite happy with yet.
